var searchData=
[
  ['t_0',['T',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'1. push_back(const T&amp;)'],['../md__r_e_a_d_m_e.html#autotoc_md6',1,'3. resize(size_t, const T&amp;)']]],
  ['t_20tt_20_3a_1',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['t_20tt_20klasė_20std_3a_3avector_20alternatyva_2',['Trečiasis darbas – &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt; klasė (std::vector alternatyva)',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['testų_20rezultatai_3',['Visų testų rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['testai_20atlikti_20su_20em_20doctest_20em_4',['&lt;em&gt;The Rule of five&lt;/em&gt; Testai atlikti su &lt;em&gt;doctest&lt;/em&gt;',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['testavimo_20aplinka_5',['Testavimo aplinka',['../md__r_e_a_d_m_e.html#autotoc_md26',1,'']]],
  ['testavimo_20rezultatai_6',['Testavimo rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['testcase_7',['TestCase',['../structdoctest_1_1detail_1_1_test_case.html',1,'doctest::detail']]],
  ['testcasedata_8',['TestCaseData',['../structdoctest_1_1_test_case_data.html',1,'doctest']]],
  ['testcaseexception_9',['TestCaseException',['../structdoctest_1_1_test_case_exception.html',1,'doctest']]],
  ['testfailureexception_10',['TestFailureException',['../structdoctest_1_1detail_1_1_test_failure_exception.html',1,'doctest::detail']]],
  ['testrunstats_11',['TestRunStats',['../structdoctest_1_1_test_run_stats.html',1,'doctest']]],
  ['testsuite_12',['TestSuite',['../structdoctest_1_1detail_1_1_test_suite.html',1,'doctest::detail']]],
  ['the_20rule_20of_20five_20em_20testai_20atlikti_20su_20em_20doctest_20em_13',['&lt;em&gt;The Rule of five&lt;/em&gt; Testai atlikti su &lt;em&gt;doctest&lt;/em&gt;',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['trečiasis_20darbas_20–_20tt_20vector_20t_20tt_20klasė_20std_3a_3avector_20alternatyva_14',['Trečiasis darbas – &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt; klasė (std::vector alternatyva)',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['true_5ftype_15',['true_type',['../structdoctest_1_1detail_1_1types_1_1true__type.html',1,'doctest::detail::types']]],
  ['tt_16',['tt',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'Executable su O1 failo dydis &lt;tt&gt;221KB&lt;/tt&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md21',1,'Executable su O2 failo dydis &lt;tt&gt;205KB&lt;/tt&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md22',1,'Executable su O3 failo dydis &lt;tt&gt;238KB&lt;/tt&gt;']]],
  ['tt_20205kb_20tt_17',['Executable su O2 failo dydis &lt;tt&gt;205KB&lt;/tt&gt;',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['tt_20221kb_20tt_18',['Executable su O1 failo dydis &lt;tt&gt;221KB&lt;/tt&gt;',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['tt_20238kb_20tt_19',['Executable su O3 failo dydis &lt;tt&gt;238KB&lt;/tt&gt;',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['tt_20_3a_20',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['tt_20ir_20tt_20vector_20t_20tt_20_3a_21',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['tt_20klasė_20std_3a_3avector_20alternatyva_22',['Trečiasis darbas – &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt; klasė (std::vector alternatyva)',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['tt_20std_3a_3avector_20tt_20ir_20tt_20vector_20t_20tt_20_3a_23',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['tt_20vector_20t_20tt_20_3a_24',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['tt_20vector_20t_20tt_20klasė_20std_3a_3avector_20alternatyva_25',['Trečiasis darbas – &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt; klasė (std::vector alternatyva)',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['tuple_26',['tuple',['../classstd_1_1tuple.html',1,'std']]],
  ['tyrimų_20rezultatai_20su_2001_20vėliavėlę_3a_27',['FAILŲ TYRIMŲ REZULTATAI SU 01 vėliavėlę:',['../md__r_e_a_d_m_e.html#autotoc_md25',1,'']]],
  ['tyrimų_20rezultatai_20su_2002_20vėliavėlę_3a_28',['FAILŲ TYRIMŲ REZULTATAI SU 02 vėliavėlę:',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['tyrimų_20rezultatai_20su_2003_20vėliavėlę_3a_29',['FAILŲ TYRIMŲ REZULTATAI SU 03 vėliavėlę:',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['tyrimų_20rezultatai_20tt_20std_3a_3avector_20tt_20ir_20tt_20vector_20t_20tt_20_3a_30',['FAILŲ TYRIMŲ REZULTATAI &lt;tt&gt;std::vector&lt;/tt&gt; ir &lt;tt&gt;Vector\&lt;T\&gt;&lt;/tt&gt;:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]]
];
